name 'nodejs'
maintainer 'Gum-Joe'
maintainer_email 'kishansambhi@hotmail.co.uk'
license 'all_rights'
description 'Installs/Configures nodejs'
long_description 'Installs/Configures nodejs'
version '0.1.0'
